# Generated by Django 2.2.1 on 2019-05-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('airing_date', models.DateField()),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('seasonend', 'End Season'), ('terminated', 'End Series'), ('announced', 'New Season')], max_length=20)),
            ],
        ),
    ]
